### ISSUE TITLE
Could you please advise what is the correct command for compressing with the lowest, "screen" quality and file size?

### ISSUE THREAD

**Issue by UtopistList** [tezzytezzy/pdf-batch-compressor#1]
Is it
pdf_batch_compressor.sh –dPDFSETTINGS=/screen
or 
pdf_batch_compressor.sh --setting=SCREEN
?

**Comment by UtopistList** [comment]
ah figured it out:
pdf_batch_compressor.sh --setting=screen

**Comment by tezzytezzy** [comment]
Yes, well done.

Three (3) options for --setting

1. **prepress** (default) Higher quality output (300 dpi) but bigger size
2. **ebook**	Medium quality output (150 dpi) with moderate output file size
3. **screen**	Lower quality output (72 dpi) but smallest possible output file size
